version: '3.4'

networks:
  backend:
services:
  herodb:
    container_name: hero-db
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
        - 8001:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pwd123!!1
      - MSSQL_PID=Developer
    networks:
      - backend
  heroapi:
    image: ${DOCKER_REGISTRY-}heroapi
    build:
      context: .
      dockerfile: HeroApi/Dockerfile
    networks:
        - backend
    ports:
        - 8002:80
    depends_on:
        - herodb
    environment:
        - DB_HOST=herodb
        - DB_NAME=HeroDb
        - DB_MSSQL_SA_PASSWORD=Pwd123!!1