version: '3.4'

networks:
  heroes:
  villains:
services:
  herodb:
    container_name: hero-db
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
        - 8001:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pwd123!!1
      - MSSQL_PID=Developer
    networks:
      - heroes
  heroapi:
    image: ${DOCKER_REGISTRY-}heroapi
    build:
      context: .
      dockerfile: HeroApi/Dockerfile
    networks:
        - heroes
    ports:
        - 8002:80
    depends_on:
        - herodb
    environment:
        - DB_HOST=herodb
        - DB_NAME=HeroDb
        - DB_MSSQL_SA_PASSWORD=Pwd123!!1
  villaindb:
    container_name: villain-db
    image: mongo:latest
    ports:
        - 8003:27017
    networks:
        - villains
  villainapi:
    image: ${DOCKER_REGISTRY-}villainapi
    build:
      context: .
      dockerfile: VillianApi/Dockerfile
    networks:
      - villains
    ports:
      - 8004:80
    depends_on:
      - villaindb
    environment:
      - DB_HOST=villaindb
      - DB_NAME=VillainDb